# Generated by Django 3.1.1 on 2020-09-23 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, unique=True)),
                ('hash', models.CharField(default='', max_length=20, unique=True)),
                ('preferred_url', models.CharField(default='', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.CharField(default='127.0.0.1', max_length=39)),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2020, 9, 23, 19, 51, 52, 236285, tzinfo=utc))),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='shortener.link')),
            ],
            options={
                'db_table': 'additional_info',
            },
        ),
    ]
