# Generated by Django 3.1.1 on 2020-09-23 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200923_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='preferred_url',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='linkinfo',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 20, 42, 31, 996972, tzinfo=utc)),
        ),
    ]
