# Generated by Django 3.1.1 on 2020-09-23 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200923_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinfo',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 20, 52, 12, 114782, tzinfo=utc)),
        ),
    ]
