# Generated by Django 3.1.1 on 2020-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200923_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='author_ip',
            field=models.CharField(default='localhost', max_length=39),
        ),
        migrations.DeleteModel(
            name='LinkInfo',
        ),
    ]
