# Generated by Django 3.1.1 on 2020-09-24 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200924_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=1000, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
